export const hydrogenMerchantCenterDomainSetup = {
  meta: {
    title: "Fixing Google Merchant Center URL Mismatches | The Portfoleyo",
    description:
      "How I resolved Google Merchant Center URL mismatch errors on a Shopify Hydrogen storefront by separating the Hydrogen and Online Store domains.",
  },
  twoColumn: {
    title: "Merchant Center Domains",
    href: "/projects/hydrogen-merchant-center-domain-setup",
    image: {
      src: "/projects/case-study-hydrogen-merchant-center-domains.jpg",
      alt: "Case Study: Resolving Google Merchant Center URL Mismatches on Shopify Hydrogen",
    },
  },
  title: "Fixing Merchant Center Product Disapprovals",
  intro:
    "Product disapprovals in Google Merchant Center can be surprisingly difficult to diagnose on a Shopify Hydrogen storefront. This case study walks through a real-world URL mismatch issue, why Shopify was generating product URLs against the wrong domain, and the changes required to resolve it ->",
  h1: "Fixing Merchant Center URL Mismatches on Shopify Hydrogen",
  subTitle:
    "Resolving feed URL mismatches between Shopify's Online Store and a Hydrogen storefront.",
  page: [
    `<h2 class="article-heading">Overview</h2>`,

    `<p>This case study covers a Google Merchant Center issue I encountered on my client's Shopify Hydrogen site, where product URLs in Google's feed didn't quite match the URLs being served by the live storefront.</p>`,

    `<p>The result wasn't great; we had product disapprovals and Merchant Center warnings that needed resolving ASAP before products could be surfaced correctly in Google Shopping.</p>`,

    `<hr class="divider" />`,

    `<h2 class="article-heading">The Problem</h2>`,

    `<p>Google Merchant Center was flagging product URL mismatches across the catalogue.</p>`,

    `<ul class="article-list">
    For example:
      <li>&bull; Feed URL: <i>my-store.myshopify.com/products/product-name</i></li>
      <li>&bull; Live URL: <i>mystore.com/products/product-name</i></li>
      <li>&bull; Result: Merchant Center mismatch errors</li>
    </ul>`,

    `<p>Because the domains didn't match, products were being disapproved and reporting in Merchant Center became unreliable.</p>`,

    `<hr class="divider" />`,

    `<h2 class="article-heading">Root Cause</h2>`,

    `<p>The issue stemmed from how Shopify handles domains when using a headless Hydrogen storefront. Shopify doesn't actually allow the same domain to be used simultaneously by both the Hydrogen storefront and the Online Store channel that's used internally by Shopify for things like feeds and integrations.</p>`,

    `<p>This meant Shopify was generating product URLs using one domain whilst customers were browsing products on another.</p>`,

    `<hr class="divider" />`,

    `<h2 class="article-heading">The Solution</h2>`,

    `<p>The fix wasn't purchasing another domain or creating a custom feed. Instead, I created a dedicated subdomain for Shopify's Online Store and allowed Hydrogen to continue using the primary domain.</p>`,

    `<p>This ensured both systems remained under the same root domain whilst avoiding Shopify's domain conflict restrictions.</p>`,

    `<hr class="divider" />`,

    `<h2 class="article-heading">Implementation</h2>`,

    `<h3 class="article-subheading">1) Create a subdomain via your provider</h3>`,

    `<ul class="article-list">
      <li>I created a dedicated subdomain: <i>checkout.my-store.com</i></li>
    </ul>`,

    `<h3 class="article-subheading">2) Update DNS</h3>`,

    `<ul class="article-list">
      <li> Within the DNS provider, I added a CNAME record pointing the new subdomain to Shopify:
 checkout → shops.myshopify.com</li>
    </ul>`,

    `<h3 class="article-subheading">3) Connect the domain in Shopify</h3>`,

    `<p>Once connected inside Shopify Admin, the new subdomain was assigned as the primary domain for the Online Store channel.</p>`,

    `<h3 class="article-subheading">4) Leave Hydrogen on the primary domain</h3>`,

    `<p>The Hydrogen storefront continued serving customers via the main domain whilst Shopify's internal systems used the subdomain.</p>`,

    `<hr class="divider" />`,

    `<h2 class="article-heading">SEO Considerations</h2>`,

    `<p>One concern was ensuring there wasn't any SEO impact from introducing a secondary domain. But as the new domain was a subdomain of the primary website and checkout pages aren't intended to rank in search engines, there was no negative SEO impact.</p>`,

    `<p>Product URLs generated by Shopify now sat under the same root domain, which resolved the Merchant Center mismatch warnings.</p>`,

    `<hr class="divider" />`,

    `<h2 class="article-heading">Feed Synchronisation</h2>`,

    `<p>After the domain changes were made, Merchant Center didn't update instantly.</p>`,

    `<ul class="article-list">
      <li>&bull; Shopify continued syncing via the Content API</li>
      <li>&bull; No manual feed upload was required</li>
      <li>&bull; Updates took several hours to appear</li>
      <li>&bull; Full propagation takes up to 48 hours to complete</li>
    </ul>`,

    `<p>Once the feed refreshed, product URLs switched to the new domain structure and thankfully the mismatch errors disappeared!</p>`,

    `<hr class="divider" />`,

    `<h2 class="article-heading">Results</h2>`,

    `<ul class="article-list">
      <li>&check; Merchant Center mismatch errors resolved</li>
      <li>&check; Product disapprovals removed</li>
      <li>&check; Hydrogen storefront remained on the primary domain</li>
      <li>&check; No SEO impact to the customer facing site</li>
      <li>&check; Future feed management simplified</li>
    </ul>`,

    `<hr class="divider" />`,

    `<h2 class="article-heading">Key Takeaways</h2>`,

    `<ul class="article-list">
      <li>&bull; Don't use the same domain for both Hydrogen and the Online Store</li>
      <li>&bull; Use a subdomain for Shopify's Online Store channel</li>
      <li>&bull; Keep Hydrogen on the primary domain</li>
      <li>&bull; Allow time for Merchant Center feeds to resynchronise</li>
      <li>&bull; Verify URLs after the sync completes</li>
    </ul>`,
  ],
};
